name: maia_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^13.2.1
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  speech_to_text: ^6.6.0 
  flutter_tts: ^4.0.0
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.3+1
  volume_watcher: ^2.0.1
  light: ^3.0.1
  fluttertoast: ^8.2.5
  xml: ^6.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
  
  fonts:
    - family: arialnarrow
      fonts:
        - asset: assets/fonts/arialnarrow.ttf
          weight: 700
        - asset: assets/fonts/arialnarrow_bold.ttf
          weight: 300